[package]
name = "fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]

[lib]
name = "fast_mvt_fuzz"
path = "src/lib.rs"

[[bin]]
name = "mvt_roundtrip"
path = "fuzz_targets/mvt_roundtrip.rs"
test = false
doc = false
bench = false

[dependencies]
arbitrary = { version = "1.4", features = ["derive"] }
buffa = "0.7.0"
fast-mvt = { path = "..", default-features = false, features = ["arbitrary", "reader", "writer"] }
libfuzzer-sys = "0.4"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
unused_qualifications = "warn"

[lints.clippy]
# Restrictions
panic_in_result_fn = "warn"
todo = "warn"
unimplemented = "warn"
# Pedantics without being too noisy
cargo = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
multiple_crate_versions = "allow"
too_many_lines = "allow"
