[package]
name = "fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[lib]
name = "fast_mvt_fuzz"
path = "src/lib.rs"

[[bin]]
name = "mvt_roundtrip"
path = "fuzz_targets/mvt_roundtrip.rs"
test = false
doc = false
bench = false

[dependencies]
arbitrary = { workspace = true }
buffa = { workspace = true }
fast-mvt = { path = "..", default-features = false, features = ["arbitrary", "reader", "writer"] }
libfuzzer-sys = "0.4"

[lints]
workspace = true
